feat: add support for jasmine-spec-reporter (displayStacktrace: true)
NickTomlin/protractor-flake pull request #70
Opened 2017-08-23 17:53 UTC by qualityshepherd

Adds support for  jasmine-spec-reporter to `standard` parser. Also, very likely resolves #54

2017-08-23 17:56 UTC, qualityshepherd commented
@NickTomlin there seems to be a bug either in your transpile, or my brain, because my change here is not making it into the dist folder. My money's on my brain 'cause I don't totally get what you're doing here. 

That said, this simple change should fix #54 that folks (and myself) are having.

2017-08-24 03:11 UTC, NickTomlin commented
Awesome!

Could you add a spec for this?

I'll take a transpilation stuff

2017-08-24 13:00 UTC, qualityshepherd commented
Ahhh... so this is an issue with `jasmine-spec-reporter` and `Protractor 5.1.2`.  You're using 4.x, which still prints `at Object.<anonymous>`. 5.1.2 prints `at UserContext.<anonymous>`. 

You want me to update the protractor version, or just add the output and a unit test (which I'm trying to figure out what the hell you're doing in there :) )?

2017-08-24 13:10 UTC, NickTomlin commented
Feel free to bump the protractor version while you are at i.

2017-08-24 14:05 UTC, qualityshepherd commented
(also asked on Gitter)
 I added a flakey test output file for jasmine-spec-reporter, and the following unit test:
```
    it('isolates individual failed specs from jasmine-spec-reporter output', () => {
      protractorFlake({maxAttempts: 3})

      spawnStub.dataCallback(failedJasmineSpecReporterTestOutput)
      spawnStub.endCallback(1)

      expect(spawnStub).to.have.been.calledWith('node', [pathToProtractor(), '--params.flake.retry', true, '--specs', '/tests/a-flakey.test.js'])
    })
```
but it's failing with this error:
```
  1) Protractor Flake failed specs isolates individual failed specs from jasmine-spec-reporter output:
     AssertionError: expected stub to have been called with arguments node, ["/Users/brine/protractor-flake/node_modules/protractor/bin/protractor", "--params.flake.retry", true, "--specs", "/tests/a-flakey.test.js"]%D
      at Context.<anonymous> (test/unit/index.test.js:103:38)
```

What am I doon wrong?

2017-08-24 14:37 UTC, qualityshepherd commented
Got it... was just braindumb. Ready for review, Nick...

2017-08-24 17:08 UTC, NickTomlin requested changes
Some very minor changes. Other than that this looks great! 

My commit linter is being super unhelpful and breaking the build so I can merge this in myself once you've updated.

2017-08-24 17:08 UTC, NickTomlin commented on test/integration/support/protractor-config/jasmine-spec-reporter.conf.js
> +'use strict';
I'd remove this file unless we need it since (we don't have an integration test that actually uses it)

2017-08-24 17:08 UTC, NickTomlin commented on package.json
> +    "jasmine-spec-reporter": "^4.2.1",
Is this dependency actually needed? I'm fine with omitting it since we have generated the static test output

2017-08-24 17:33 UTC, wswebcreation commented
@qualityshepherd 

Tnx for this PR, I didn't had the time to look at this because the sun didn't let me (something called vacation 😁).

Maybe something not in scope of this change, but is there a way in Jasmine that we can log a line of text to the console on every failed test?

That would make the reading of the log for protractor-flake much easier. Currently working on that for the CucumberJS parser

2017-08-24 17:37 UTC, qualityshepherd commented on test/integration/support/protractor-config/jasmine-spec-reporter.conf.js
> +'use strict';
Cool... wasn't sure if you wanted a repeatable conf for the future [WOOSH SOUND]. The answer is no :) It's gone.

2017-08-24 17:38 UTC, qualityshepherd commented on package.json
> +    "jasmine-spec-reporter": "^4.2.1",
Not now that the conf using it is gone

2017-08-24 17:42 UTC, qualityshepherd commented
@wswebcreation yeah, definitely out of scope for _this_ pr, but would be easy enough to do... 

@NickTomlin all wrapped up. Though one last question... do we want this fix in `multi` too?

2017-08-24 17:51 UTC, wswebcreation commented
@qualityshepherd 

I would advice to also fix the multi

Secondly, if it's easy to fix for Jasmine with a logline, can you give me a direction so I can create aPR for CucumberJS and Jasmine?

2017-08-24 18:46 UTC, NickTomlin commented
@wswebcreation @wswebcreation great point on multi, I always forget about that one :( I think we should!

It would be interesting to expose separate reporters for jasmine/cucumber that do this logging. Let's keep that discussion going in another PR. Do one of you want to open up an issue to track it?

2017-08-24 19:51 UTC, wswebcreation commented
Will create an issue for this

2017-08-24 20:02 UTC, qualityshepherd commented
@NickTomlin cool... that was easy, as the `multi` parser doesn't needs a change for this. So I just added a unit test.

2017-08-24 21:04 UTC, wswebcreation commented
@NickTomlin  and @qualityshepherd 

I've created 2 new issues (Feature request), https://github.com/NickTomlin/protractor-flake/issues/71 and https://github.com/NickTomlin/protractor-flake/issues/72.

2017-08-24 22:32 UTC, NickTomlin commented
I've gone ahead and removed conventional changelog linting on master, so could you rebase to re-run the integration tests? In my other runs it seems like bumping protractor breaks the integration tests. We should either fix them or downgrade for now and bump later.

2017-08-24 22:56 UTC, merged

2017-08-24 22:57 UTC, NickTomlin commented
I went ahead and made these changes myself and merged this in. Thanks!

2017-08-24 23:09 UTC, qualityshepherd commented
Cool... thanks Nick!